before:
  hooks:
    - go mod download

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w

kos:
  - repository: 'ghcr.io/lesuisse/shelly-ht-action-prometheus'
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    creation_time: '{{ .CommitTimestamp }}'
    ko_data_creation_time: '{{ .CommitTimestamp }}'
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

docker_signs:
  - artifacts: manifests
    cmd: cosign
    args: ["sign", "${artifact}@${digest}", "--yes"]

signs:
  - id: cosign-keyless
    signature: "${artifact}.bundle"
    cmd: cosign
    args: ["sign-blob", "--bundle", "${signature}", "--yes", "${artifact}"]
    artifacts: all
sboms:
  - artifacts: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
