before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

dockers:
  - image_templates:
      - 'ghcr.io/lesuisse/{{ .ProjectName }}:{{ .Version }}-amd64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/amd64"
    goarch: amd64
  - image_templates:
      - 'ghcr.io/lesuisse/{{ .ProjectName }}:{{ .Version }}-arm64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: 'ghcr.io/lesuisse/{{ .ProjectName }}:{{ .Version }}'
    image_templates:
      - 'ghcr.io/lesuisse/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'ghcr.io/lesuisse/{{ .ProjectName }}:{{ .Version }}-arm64'
  - name_template: 'ghcr.io/lesuisse/{{ .ProjectName }}:latest'
    image_templates:
      - 'ghcr.io/lesuisse/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'ghcr.io/lesuisse/{{ .ProjectName }}:{{ .Version }}-arm64'

signs:
  - id: cosign-keyless
    signature: "${artifact}.bundle"
    cmd: cosign
    args: ["sign-blob", "--bundle", "${signature}", "--yes", "${artifact}"]
    artifacts: all

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc

release:
  extra_files:
    - glob: dist/*.sig
