name: CI

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # tag=v3.4.0
      - uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # tag=v20
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Run GoReleaser
        run: nix develop --command goreleaser release --snapshot --rm-dist
  static_analysis:
    runs-on: ubuntu-22.04
    name: Run static analysis and linting
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # tag=v3.4.0
      - uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # tag=v20
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Go fmt
        run: nix develop --command sh -c 'diff -u <(echo -n) <(gofmt -d -s *.go ./)'
      - name: Go vet
        run: nix develop --command go vet ./...
