name: CI

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.16.0'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.0.0
        with:
          version: latest
          args: release --snapshot --rm-dist
  static_analysis:
    runs-on: ubuntu-20.04
    name: Run static analysis and linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.15.0'
      - name: Go fmt
        run: diff -u <(echo -n) <(gofmt -d -s *.go gpg/)
      - name: Go vet
        run: go vet ./...
