name: CI

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    name: Build
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # tag=v4.0.0
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # tag=v23
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Run GoReleaser
        run: nix develop --command goreleaser release --snapshot --clean
  static_analysis:
    runs-on: ubuntu-22.04
    name: Run static analysis and linting
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # tag=v4.0.0
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # tag=v23
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: golangci-lint
        run: nix develop --command golangci-lint run
