name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.16.0'
      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.7.0
      - name: Install Cosign private key
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: echo "$COSIGN_PRIVATE_KEY" > /dev/shm/cosign_private_key
      - name: Log into ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.1.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_EXPERIMENTAL: 1
      - name: Sign Docker images
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_EXPERIMENTAL: 1
        run: cosign sign -key /dev/shm/cosign_private_key -r ghcr.io/lesuisse/shelly-ht-action-prometheus:latest
      - name: Remove installed Cosign private key
        run: rm /dev/shm/cosign_private_key
        if: ${{ always() }}
